apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: search-service
  labels:
    app: search-service
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - name: http
      port: 80
      targetPort: http
