-- source DB schema. Postgres (운영) + H2 (dev) 호환을 위해 표준 SQL 만 사용.

CREATE TABLE products (
    id              VARCHAR(64)   PRIMARY KEY,
    name            VARCHAR(200)  NOT NULL,
    brand           VARCHAR(100)  NOT NULL,
    category        VARCHAR(30)   NOT NULL,
    sizes           VARCHAR(500)  NOT NULL,
    price_won       BIGINT        NOT NULL,
    stock_quantity  INT           NOT NULL,
    status          VARCHAR(30)   NOT NULL,
    version         BIGINT        NOT NULL,
    released_at     TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

CREATE INDEX ix_products_brand   ON products (brand);
CREATE INDEX ix_products_status  ON products (status);

-- 검색 클릭 로그 — boost rule 학습 자료. product_id + occurred_at 인덱스로
-- "특정 product 의 since 이후 click 합산" 쿼리 빠르게.
CREATE TABLE search_clicks (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_id    VARCHAR(64)  NOT NULL,
    user_id      VARCHAR(64),
    product_id   VARCHAR(64)  NOT NULL,
    keyword      VARCHAR(200) NOT NULL,
    rank_position INT         NOT NULL,
    occurred_at  TIMESTAMP    NOT NULL
);

CREATE INDEX ix_search_clicks_product ON search_clicks (product_id, occurred_at);

-- CDC outbox — Debezium 의 단순 시뮬. Relay 가 published_at NULL 인 행만
-- polling 해 Kafka 로 발행 후 published_at 채움.
CREATE TABLE product_change_outbox (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op            VARCHAR(16)   NOT NULL,
    product_id    VARCHAR(64)   NOT NULL,
    version       BIGINT        NOT NULL,
    payload       TEXT,
    occurred_at   TIMESTAMP     NOT NULL,
    published_at  TIMESTAMP
);

CREATE INDEX ix_outbox_published ON product_change_outbox (published_at, id);
