-- 검색 이벤트 로그 — 분석 (top queries / zero-result / latency / CTR) 자료 (ADR-0018).
--
-- (occurred_at) — 모든 분석 query 가 시간 구간 필터.
-- (occurred_at, keyword) — top queries / zero-result group-by 의 covering.

CREATE TABLE search_events (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_id     VARCHAR(64)  NOT NULL,
    keyword       VARCHAR(200) NOT NULL,
    user_id       VARCHAR(64),
    result_count  BIGINT       NOT NULL,
    latency_ms    BIGINT       NOT NULL,
    occurred_at   TIMESTAMP    NOT NULL
);

CREATE INDEX ix_search_events_occurred         ON search_events (occurred_at);
CREATE INDEX ix_search_events_occurred_keyword ON search_events (occurred_at, keyword);
